<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SystemModule\SystemModule.csproj" />
    <ProjectReference Include="..\..\GameGate-CS\GameGate.csproj" />
  </ItemGroup>
</Project>
