<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>NativeWinExpChainCheck</AssemblyName>
    <RootNamespace>NativeWinExpChainCheck</RootNamespace>
    <OutputPath>..\..\..\Build\AuditTools\NativeWinExpChainCheck\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\GameSvr\GameSvr.csproj" />
  </ItemGroup>

</Project>
