<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SystemModule\SystemModule.csproj" />
    <Compile Include="..\..\GameSvr\Services\NativeRelationService.cs"
             Link="NativeRelationService.cs" />
  </ItemGroup>
</Project>
